name: unipi
version: "0.0.1"
summary: unipi stack 
description: |
  unipi stack

confinement: strict
grade: stable

apps:
    neuron-server:
        command: opt/neurontcp/neuron_tcp_server -p 502 --check-firmware
        daemon: simple
        plugs: [network, network-bind]

parts:
    neuron:
        plugin: make
        source: neuron_tcp_server
        build-packages: [libmodbus-dev ]

